CREATE TABLE DB_KEY_STORE 
(
LABEL VARCHAR(255) NOT NULL,
CIPHER_KEY CLOB,
CERT CLOB,
CHAIN CLOB,
KEYPASSWORD VARCHAR(256),
CREATED DATE
);

CREATE TABLE DB_KEY_STORE_METADATA
(
PROPERTY_KEY VARCHAR(255) NOT NULL,
PROPERTY_VALUE CLOB
);

ALTER TABLE DB_KEY_STORE ADD PRIMARY KEY (LABEL);

ALTER TABLE DB_KEY_STORE_METADATA ADD PRIMARY KEY (PROPERTY_KEY);